### ISSUE TITLE
Image de l'interface pour le README

### ISSUE THREAD

**Issue by MarionLnd** [MarionLnd/SviacamReprise#18]
<img width="1803" alt="Capture d’écran 2020-11-09 à 20 28 58" src="https://user-images.githubusercontent.com/31901812/98645777-b6f86080-2332-11eb-8ac3-04801bfa5a0d.png">

**Comment by MarionLnd** [comment]
![WhatsApp Image 2020-11-10 at 11 26 13](https://user-images.githubusercontent.com/31901812/98662673-6f7ccf00-2348-11eb-848b-b5e6495f20d3.jpeg)
Interface 2 (fenêtres de détection activées)

**Comment by MarionLnd** [comment]
![WhatsApp Image 2020-11-10 at 11 38 21 (2)](https://user-images.githubusercontent.com/31901812/98663693-b3240880-2349-11eb-83f5-e6c76e7b38d9.jpeg)
![WhatsApp Image 2020-11-10 at 11 38 22](https://user-images.githubusercontent.com/31901812/98663699-b5866280-2349-11eb-965a-4436f92b1968.jpeg)
![WhatsApp Image 2020-11-10 at 11 38 21 (1)](https://user-images.githubusercontent.com/31901812/98663702-b61ef900-2349-11eb-898a-a309fcd23b65.jpeg)
![WhatsApp Image 2020-11-10 at 11 38 21](https://user-images.githubusercontent.com/31901812/98663703-b6b78f80-2349-11eb-9c0c-b7af6766a465.jpeg)
Interfaces mouvements des doigts

**Comment by MarionLnd** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/31901812/98664800-1e220f00-234b-11eb-9795-eaf45e632e83.gif)
GIF du mouvement

**Comment by soukaMoutaoukil** [comment]
Done
